regions = {"Qoraqalpog‘iston Respublikasi": ["Amudaryo tumani", "Kegayli tumani", "Qorao‘zak tumani", "Mo‘ynoq tumani",
                                             "Nukus shahri", "To‘rtko‘l tumani", "Chimboy tumani", "Ellikqal‘a tumani",
                                             'Beruniy tumani', 'Qonliko‘l tumani', 'Qo‘ng‘irot tumani', 'Nukus tumani',
                                             'Taxtako‘pir tumani', 'Xo‘jayli tumani', 'Shumanay tumani',
                                             'Taxiatosh shahri'],
           'Andijon viloyati': ["Andijon shahri", "Asaka tumani", "Buloqboshi tumani", "Jalaquduq tumani",
                                "Qorasuv shahri", "Marhamat tumani", "Paxtaobod tumani", "Xonabod tumani",
                                "Shahrixon tumani", 'Andijon tumani', 'Baliqchi tumani', 'Bo‘z tumani',
                                'Izboskan tumani', 'Qo‘rg‘ontepa tumani', 'Oltinko‘l tumani', 'Ulug‘nor tumani',
                                'Xo‘jaobod tumani', 'Asaka shahri'],
           "Buxoro viloyati": ["Buxoro shahri", "Buxoro tumani",
                               "Vobkent tumani", "G‘ijduvon tumani",
                               "Jondor tumani", "Kogon tumani",
                               "Kogon shahri", "Qorako‘l tumani",
                               "Qorovulbozor tumani", "Olot tumani",
                               "Peshku tumani", "Romitan tumani",
                               "Shofirkon tumani", "Galiosiyo tumani"],
           'Jizzax viloyati': ["Arnasoy tumani", "Baxmal tumani",
                               "G‘allaorol tumani", "Do‘stlik tumani",
                               "Sh.Rashidov tumani", "Jizzax shahri",
                               "Zarbdor tumani", "Zafarobod tumani",
                               "Zomin tumani", "Mirzacho‘l tumani",
                               "Paxtakor tumani", "Forish tumani",
                               "Yangiobod tumani"],
           "Qashqadaryo viloyati": ["G‘uzor tumani", "Dehqonobod tumani",
                                    "Qamashi tumani", "Qarshi tumani",
                                    "Qarshi shahri", "Kasbi tumani",
                                    "Kitob tumani", "Koson tumani",
                                    "Mirishkor tumani", "Muborak tumani",
                                    "Nishon tumani", "Chiroqchi tumani",
                                    "Shahrisabz tumani", "Yakkabog‘ tumani"],
           'Navoiy viloyati': ["Zarafshon shahri", "Karman tumani",
                               "Qiziltepa tumani", "Konimex tumani",
                               "Navbahor tumani", "Navoiy shahri",
                               "Nurota tumani", "Tomdi tumani",
                               "Uchquduq tumani", "Xatirchi tumani", ],
           "Namangan viloyati": ["Kosonsoy tumani", "Mingbuloq tumani",
                                 "Namangan tumani", "Namangan shahri",
                                 "Norin tumani", "Pop tumani",
                                 "To‘raqo‘rg‘on tumani", "Uychi tumani",
                                 "Uchqo‘rg‘on tumani", "Chortoq tumani",
                                 "Chust tumani", "Yangiqo‘rg‘on tumani"],
           'Samarqand viloyati': ["Bulung‘ur tumani", "Jomboy tumani",
                                  "Ishtixon tumani", "Kattaqo‘rg‘on tumani",
                                  "Kattaqo‘rg‘on shahri", "Qo‘shrabot tumani",
                                  "Narpay tumani", "Nurabod tumani",
                                  "Oqdaryo tumani", "Payariq tumani",
                                  "Pastarg‘om tumani", "Paxtachi tumani",
                                  "Samarqand tumani", "Samarqand shahri",
                                  "Toyloq tumani", "Urgut tumani", ],
           "Surxandaryo viloyati": ["Angor tumani", "Boysun tumani",
                                    "Denov tumani", "Jarqo‘rg‘on tumani",
                                    "Qiziriq tumani", "Qumqo‘rg‘on tumani",
                                    "Muzrabot tumani", "Oltinsoy tumani",
                                    "Sariosiyo tumani", "Termiz tumani",
                                    "Termiz shahri", "Uzun tumani",
                                    "Sherobod tumani", "Sho‘rchi tumani",
                                    "Bandixon tumani"],
           'Sirdaryo viloyati': ["Boyovut tumani", "Guliston tumani",
                                 "Guliston shahri", "Mirzaobod tumani",
                                 "Oqoltin tumani", "Sayxunobod tumani",
                                 "Sardoba tumani", "Sirdaryo tumani",
                                 "Xavos tumani", "Shirin shahri",
                                 "Yangiyer shahri"],
           "Toshkent viloyati": ["Angren shahri", "Bekobod tumani",
                                 "Bekobod shahri", "Bo‘ka tumani",
                                 "Bo‘stonliq tumani", "Zangiota tumani",
                                 "Qibray tumani", "Quyichirchiq tumani",
                                 "Oqqo‘rg‘on tumani", "Olmaliq shahri",
                                 "Ohangaron tumani", "Parkent tumani",
                                 "Piskent tumani", "O‘rtachirchiq tumani",
                                 "Chinoz tumani", "Chirchiq shahri",
                                 "Yuqorichirchiq tumani", "Yangiyo‘l tumani",
                                 "Ohangaron shahri", "Yangiyo‘l shahri",
                                 "Toshkent tumani"],
           'Farg\'ona viloyati': ["Beshariq tumani", "Bag‘dod tumani",
                                  "Buvayda tumani", "Dang‘ara tumani",
                                  "Yozyovon tumani", "Quva tumani",
                                  "Quvasoy shahri", "Qo‘qon shahri",
                                  "Qo‘shtepa tumani", "Marg‘ilon shahri",
                                  "Oltiariq tumani", "Rishton tumani",
                                  "So‘x tumani", "Toshloq tumani",
                                  "Uchko‘prik tumani", "O‘zbekiston tumani",
                                  "Farg‘ona tumani", "Farg‘ona shahri",
                                  "Furqat tumani"],
           "Xorazm viloyati": ["Bog‘ot tumani", "Gurlan tumani",
                               "Qo‘shko‘pir tumani", "Urganch tumani",
                               "Urganch shahri", "Xiva tumani",
                               "Xazorasp tumani", "Xonqa tumani",
                               "Shovot tumani", "Yangiariq tumani",
                               "Yangibozor tumani", "Xiva shahri",
                               "Tuproqqal'a tumani"],
           'Toshkent Shahri': ["Bektemir tumani", "Mirzo Ulug'bek tumani",
                               "Mirobod tumani", "Olmazor tumani",
                               "Sirg'ali tumani", "Uchtepa tumani",
                               "Yashnobod tumani", "Chilonzor tumani",
                               "Shayxontohur tumani", "Yunusobod tumani",
                               "Yakkasaroy tumani", "Yangihayot tumani"]
           }

languages = {'uz': {

    }
}
