# Generated by Django 4.2.16 on 2024-11-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('education_place', models.CharField(max_length=100)),
                ('family_status', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('branch_desire', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=25)),
                ('worked_before', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('extra_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shirt_size', models.CharField(max_length=25)),
                ('is_studying', models.CharField(max_length=5)),
                ('education_type', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=255)),
                ('work_experience', models.TextField()),
                ('programms_experience', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('salary', models.PositiveIntegerField()),
                ('is_familiar_works_here', models.CharField(max_length=100)),
                ('is_uzbek_citizen', models.CharField(max_length=5)),
                ('is_working_now', models.CharField(max_length=5)),
                ('from_vacancy_info', models.CharField(max_length=100)),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
