# Generated by Django 4.2.16 on 2024-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
