# Generated by Django 4.2.16 on 2024-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_resume_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birthday',
            field=models.CharField(max_length=100),
        ),
    ]
