# Generated by Django 4.2.16 on 2024-11-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_resume_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
